import { ActivityType } from 'discord.js'
import { Bot } from '../classes'

export default class Status {
  private static INTERVAL_MS = 1000 * 30

  private static statuses = [
    'nihahahaha',
    'i love komimau',
    'wiggles your balls',
    'unwiggles your balls',
    'AaAaAaAAaAaAAaAaAaAaAAaAaAAaAaAaAaAAaAaAAa',
    'whoever reads Statuses is gay',
    'omg it migu',
    'your bra strap is visible',
    '...',
    'busy with your mom rn',
    '🍀',
    '69',
    'ちんちん小さいですね',
    'cum',
    '💵',
    'i only speak facts',
    'yuri',
    'i have an onlyfans',
    "it's only $5 a month",
    'is it hot or is it just me?',
    "i'm the best",
    'h',
    "i've seen your porn collection",
    '¿pero qué pasa?',
    'i draw nsfw btw',
    "i'm gonna jump",
    'http://localhost:5173',
    'who cares?',
    '🐢',
    'boost for boob pic',
    'why so serious?',
    'you know the rules, and so do i',
    "don't even think about it",
    "i'll lick your armpits",
    'so gay',
    'yaoi',
    "i'm broke, give money",
    'i sell feet pics',
    'just $80 an hour',
    '🍋🍈🍪🍋🍈🍪🍋🍈🍋🍈🍪🍋🍈🍪🍪',
    'so based 🗿',
    'https://youtu.be/dQw4w9WgXcQ',
    "you can't fix me",
    'i can fix you',
    'bitch',
    'fuck',
    'discord.gg/komimau',
    '3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534',
    'NIHAHAHAHHAHAHAHAHAHAHHAHAHAHHAHAHA',
    'get shit on',
    'double rainbow',
    "i'm faker",
    '727',
    '🐧',
    'when you see it',
    'komimau tentacle hentai when?',
    '💀🔫',
    '鬱',
    'FUCK',
    'depression',
    'cumtastic',
    '190.102.79.253',
    'sob',
    'paypal me $30000',
    '<status />',
    'suck on my dih',
    '🍦🍧🍨🍩🍪🎂🍰🧁🥧🍫🍭',
    'i like pink',
    'lesbian sex',
    "what're you looking at?",
    'smell my armpits',
    "i'll fuck you up",
    'a',
    'switch to linux',
    'english or spanish',
    'lemon melon cookie lemon melon cookie lemon melon lemon melon cookie lemon melon cookie cookie',
    'fucks your mom',
    'unfucks your mom',
    'lick me',
    '🛹',
    "i'm crine",
    "i'm unemployed",
    'i could be your therapist',
    'best day of my life',
    'worst day of my life',
    'fudge',
    'fight me bitch',
    "flickin' da bean",
    'ta mère',
    'ur mom',
    "you're funny",
    'hot',
    "don't take me seriously",
    '6-7',
    'lorem ipsum dolor sit amet',
    "i'm an expert in foot licking",
    '🍆💦🍑',
    "abcdefghi'mgayjklmnopqrstuvwxyz",
    "you can't hide from me",
    'i got hairy toes',
    'UWAAAAAAAAAAAH',
    'procrastinating atm',
    'play osu',
    'click the circles',
    'slay',
    'i could do stand up comedy',
    '💅',
    'use me daddy',
    'SHIT',
    "i'm angy",
    'hatsune miku',
    'your mom fat 🗣️🔥',
    'L',
    'sesbian lex',
    'i use arch btw',
    'conclusion: you suck',
    'lowercase supremacy',
    'git gud, kid',
    '😭💢💢💢',
    'komimau is cool',
    'i nut',
    'need more statuses',
  ]

  private static index = 0

  private static next() {
    const status = Status.statuses[Status.index++ % Status.statuses.length]!

    Bot.client.user?.setActivity(status, {
      type: ActivityType.Custom,
    })
  }

  public static cycle() {
    Status.next()
    setInterval(() => Status.next(), Status.INTERVAL_MS)
  }
}
